runtime: python-3.11.14
services:
  - type: web
    name: flask-chat-app
    env: python
    runtime: python-3.11.14
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --threads 10 wsgi:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chat_db
          property: connectionString

databases:
  - name: chat_db
    plan: free